#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only

set -euo pipefail

ssh_user=${1:?missing guest user}
desktop_stamp=/var/lib/castkms-vm/desktop-v1
gdm_conf=/etc/gdm/custom.conf

if test ! -e "$desktop_stamp"; then
	sudo dnf -y -q --setopt=install_weak_deps=False install \
		dbus-daemon \
		gdm \
		gnome-session-wayland-session \
		gnome-settings-daemon \
		gnome-shell \
		mesa-dri-drivers \
		mesa-libgbm \
		mesa-vulkan-drivers \
		mutter
	sudo mkdir -p "$(dirname -- "$desktop_stamp")"
	sudo touch "$desktop_stamp"
fi

sudo usermod -aG video,render,input "$ssh_user"
sudo passwd -d "$ssh_user"

sudo tee "$gdm_conf" >/dev/null <<EOF
# Generated by castkms-vm desktop-provision
[daemon]
WaylandEnable=true
AutomaticLoginEnable=true
AutomaticLogin=$ssh_user
EOF

sudo systemctl set-default graphical.target
sudo systemctl enable gdm.service
sudo systemctl disable --now gnome-initial-setup-first-login.service \
	2>/dev/null || true

printf 'desktop_user=%s\n' "$ssh_user"
printf 'graphical_target=%s\n' "$(systemctl get-default)"
printf 'gdm_enabled=%s\n' "$(systemctl is-enabled gdm.service)"
